name: Prettier code formatter

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push auto-formatted commits back to the repo
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }} # Ensures it checks out the correct branch on PRs

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Prettier 💾
        run: npm install --save-dev --save-exact prettier @shopify/prettier-plugin-liquid

      - name: Run Prettier (Write) ✍️
        run: npx prettier . --write

      - name: Auto-commit formatted files 🚀
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format code with Prettier"
          branch: ${{ github.head_ref || github.ref }}
